title: Thunder Engine
description: Free and open-source multi-functional lightweight game engine.
baseurl: ""
url: "https://thunderengine.org"

include:
  - _pages

markdown: kramdown
google_analytics: "G-F5768C316N"

plugins:
  - jekyll-feed
  
feed:
  categories:
    - blog
    - learn
  posts_limit: 10
  